const produkShopee = [
  {
    nama: "Tensimeter Digital Akurat",
    harga: "Rp 70.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134207-8224r-mi1edow0vyf74c@resize_w900_nl.webp"
  },
  {
     nama: "Easytouch 3 in 1",
    harga: "Rp 250.000",
    gambar: "https://cf.shopee.co.id/file/id-11134207-8224u-mi2meeu04s938f_tn"
  },
  {
     nama: "Tensimeter Digital iTrust FC BP121",
    harga: "Rp 140.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134207-82252-mib515ngufwj77@resize_w900_nl.webp"
  },
  {
    nama: "Tensimeter Digital Omron HEM-7124",
    harga: "Rp 360.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134207-7r98y-ltq8vyk8y4gz03@resize_w900_nl.webp"
  },
  {
    nama: "Nebulizer portable",
    harga: "Rp 65.000",
    gambar: "https://upload.jaknot.com/2025/09/images/products/9f0fe9/original/taffomicron-alat-terapi-pernapasan-mesh-nebulizer-portable-inhaler-jsl-w302.jpg"
  },
   {
    nama: "Tensimeter Taff omicron BW750",
    harga: "Rp 130.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134275-7ra0g-mct0thw4rozb21@resize_w900_nl.webp"
  },
  {
    nama: "Termometer digital-Termoone",
    harga: "Rp 20.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134207-7rbke-m7u6s7hfbl5l86@resize_w900_nl.webp"
  },
   {
    nama: "Termogun",
    harga: "Rp 55.000",
    gambar: "https://down-id.img.susercontent.com/file/id-11134207-7ras8-m62e7pp4jwg603@resize_w900_nl.webp"
  },
  { nama: "Termometer digital - Thermoone", harga: "Rp 20.000", gambar: "logo.png" },
  { nama: "Cek gula darah - Sinoheart", harga: "Rp 50.000", gambar: "logo.png" },
  { nama: "Alcohol swab - Onemed", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Blood lancets - Onemed", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Termometer tembak - Omicron", harga: "Rp 55.000", gambar: "logo.png" },
  { nama: "Set Rawat Luka - Onemed", harga: "Rp 17.000", gambar: "logo.png" },
  { nama: "Sarung Tangan M - Safegloves", harga: "Rp 45.000", gambar: "logo.png" },
  { nama: "Kotak P3K - Onemed", harga: "Rp 35.000", gambar: "logo.png" },
  { nama: "Ultrafix 5x1cm - Onemed", harga: "Rp 5.000", gambar: "logo.png" },
  { nama: "Tensimeter digital", harga: "Rp 70.000", gambar: "logo.png" },
  { nama: "Plesterin WP - Onemed", harga: "Rp 1.000", gambar: "logo.png" },
  { nama: "Termometer digital - GP Care", harga: "Rp 18.000", gambar: "logo.png" },
  { nama: "Alkohol 70% 100ml - LSI", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "Povidone Iodine 30ml - Onemed", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "Test Pack - Onemed", harga: "Rp 5.000", gambar: "logo.png" },
  { nama: "I.V. Catheter No 22 - GEA", harga: "Rp 8.500", gambar: "logo.png" },
  { nama: "Pulse Oximeter", harga: "Rp 57.000", gambar: "logo.png" },
  { nama: "Mesin Nebulizer - Upheal", harga8: "Rp 76.500", gambar: "logo.png" },
  { nama: "Celana Sunat", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Tensimeter pergelangan - Omicron", harga: "Rp 120.000", gambar: "logo.png" },
  { nama: "Kasa hidrofik 16x16 - Narita", harga: "Rp 5.000", gambar: "logo.png" },
  { nama: "NGT 18Fr - Onemed", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Foley Catheter 18Fr - GEA", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Nasal Dewasa - GEA", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Syringe 50cc NT - Onemed", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "I.V. Catheter No 22G - Healthcare", harga: "Rp 8.500", gambar: "logo.png" },
  { nama: "I.V. Catheter No 20G - Healthcare", harga: "Rp 8.500", gambar: "logo.png" },
  { nama: "Infus set - Onehealth", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "Alcohol Pads - Avico", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Plesterin bulat soft - Plesterin", harga: "Rp 500", gambar: "logo.png" },
  { nama: "Syringe 5ml - Onehealth", harga: "Rp 1.000", gambar: "logo.png" },
  { nama: "Syringe 3ml - Onehealth", harga: "Rp 1.500", gambar: "logo.png" },
  { nama: "Syringe 10ml - Onehealth", harga: "Rp 2.000", gambar: "logo.png" },
  { nama: "Double spike - Onemed", harga: "Rp 5.000", gambar: "logo.png" },
  { nama: "Urin bag - Onemed", harga: "Rp 12.000", gambar: "logo.png" },
  { nama: "Needle No 24 - Terumo", harga: "Rp 1.000", gambar: "logo.png" },
  { nama: "Stetoskop - Onemed", harga: "Rp 40.000", gambar: "logo.png" },
  { nama: "Tourniquet - Onemed", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Pispot - Onemed", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "Strip Chole - Easytouch", harga: "Rp 190.000", gambar: "logo.png" },
  { nama: "Alat penggerus - Onemed", harga: "Rp 25.000", gambar: "logo.png" },
  { nama: "Wash gloves - T-Towel", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Alkohol 70% 100ml - Onemed", harga: "Rp 10.000", gambar: "logo.png" },
  { nama: "Tensimeter digital - Omron", harga: "Rp 360.000", gambar: "logo.png" },
  { nama: "Alkohol 70% 300ml - Onemed", harga: "Rp 20.000", gambar: "logo.png" },
  { nama: "Tensimeter digital - Omicron", harga: "Rp 80.000", gambar: "logo.png" },
  { nama: "Strip Glucosa 25 - Sinoheart", harga: "Rp 65.000", gambar: "logo.png" },
  { nama: "Kasur decubitus - Onemed", harga: "Rp 400.000", gambar: "logo.png" },
  { nama: "Alat Stik 3 in 1 - Easytouch", harga: "Rp 250.000", gambar: "logo.png" },
  { nama: "Strip Chole - Easytouch", harga: "Rp 190.000", gambar: "logo.png" },
  { nama: "Tensimeter manual - Onemed", harga: "Rp 100.000", gambar: "logo.png" },
  { nama: "Syringe 50cc LT - Onemed", harga: "Rp 12.000", gambar: "logo.png" },
  { nama: "Urin bag - GEA", harga: "Rp 9.000", gambar: "logo.png" },
  { nama: "Tensi + Stetoskop - Onemed", harga: "Rp 135.000", gambar: "logo.png" },
  { nama: "Arm Sling - GlowMed", harga: "Rp 32.000", gambar: "logo.png" },
  { nama: "Wing needle - Onemed", harga: "Rp 3.000", gambar: "logo.png" },
  { nama: "Plester coklat - Chilli Plast", harga: "Rp 2.000", gambar: "logo.png" },
  { nama: "Tensimeter BW750 - Omicron", harga: "Rp 120.000", gambar: "logo.png" },
  { nama: "Gel Jelly Lubricant - Onemed", harga: "Rp 35.000", gambar: "logo.png" },
  { nama: "Oximeter saturasi - Omicron", harga: "Rp 130.000", gambar: "logo.png" },
  { nama: "Tensimeter digital - iTrust BP 121", harga: "Rp 140.000", gambar: "logo.png" },
  { nama: "Oximeter saturasi anak - Omicron", harga: "Rp 55.000", gambar: "logo.png" },
  { nama: "Wash gloves 4 - Onecleane", harga: "Rp 15.000", gambar: "logo.png" },
  { nama: "Oximeter - LK88", harga: "Rp 50.000", gambar: "logo.png" },
  { nama: "Thermogun - GP 100", harga: "Rp 50.000", gambar: "logo.png" },
  { nama: "Tensimeter digital - Sinocare BA801", harga: "Rp 250.000", gambar: "logo.png" },
  { nama: "Alat cek gula darah - Sinocare 50", harga: "Rp 150.000", gambar: "logo.png" }
];
